# Generated by Django 5.0.7 on 2024-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FT_App', '0002_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
