# Generated by Django 5.0.7 on 2024-07-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FT_App', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='\\post_images'),
        ),
    ]
