# Generated by Django 5.0.7 on 2024-07-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FT_App', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
