# Generated by Django 5.0.7 on 2024-07-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FT_App', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Image',
        ),
    ]
